package: rootly
generate:
  types: true
  server: true
  models: true
  client: true
output: rootly-schema.gen.go
output-options:
  exclude-schemas:
    - new_dashboard_panel
    - update_dashboard_panel
    - dashboard_panel_list
    - dashboard_panel
    - dashboard_panel_response
